name: "my_project"
dependencies:
  antlr4: 4.9.3

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.10
  build_web_compilers: ^3.2.3
  codemirror: ^0.7.3+5.65.2

environment:
  sdk: ">=2.12.0 <3.0.0"
